name: "Export Godot"

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: 
      - release
      - staging
      - main

env:
  GODOT_VERSION: 3.4.4
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  ITCHIO_USERNAME: ${{ secrets.ITCHIO_USERNAME }}
  ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}
  git_branch: ${{ github.ref_name }}

jobs:

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - run: ./run prepare:ci
      - run: ./run export:linux
      - run: ./run push:linux
      - name: Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux
      - name: Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/linux/*
          tag: linux
          file_glob: true
          overwrite: true

  export-win:
    name: Windows Export
    runs-on: ubuntu-latest
    container: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - run: ./run prepare:ci
      - run: ./run export:windows
      - run: ./run push:windows
      - name: Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows
      - name: Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/windows/*
          tag: windows
          file_glob: true
          overwrite: true

  export-osx:
    name: OSX Export
    runs-on: ubuntu-latest
    container: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - run: ./run prepare:ci
      - run: ./run export:osx
      - run: ./run push:osx
      - name: Artifact
        uses: actions/upload-artifact@v1
        with:
          name: osx
          path: build/osx
      - name: Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/osx/*
          tag: osx
          file_glob: true
          overwrite: true
  

  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - run: ./run prepare:ci
      #- if: ${{ github.ref == 'refs/heads/release' }}
      - run: ./run export:web
      - run: ./run push:web
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/web
          clean: false
